### PR TITLE
Update deprecated set-output command

### PR DESCRIPTION
**Pull request by peterdeme**
@tdemin can you take a look? 🙏 

Fixes the following warning:

image

### CODE REVIEW

**Review by tdemin — APPROVED** [review]
LGTM, thanks :pray:

**Comment by tdemin** [comment]
Apparently relying on a random repository from the internet for testing which has since disappeared wasn't the smartest idea I've ever come up with. :D

I'll change this to another repo in a separate pull request and we'll rebase this against the main branch with tests working properly.

**Comment by peterdeme** [comment]
@tdemin awesome 🙏

**Comment by tdemin** [comment]
@peterdeme can you please rebase this patch against the current main? I've fixed the tests in bde4928d0ca16ffbd570cac532beb04f7f0acb7b.

**Comment by peterdeme** [comment]
@tdemin done

**Pull request merged**
